### ISSUE TITLE
Standardize and Optimize React

### ISSUE THREAD

**Issue by aydreeihn** [osTicket/roadmap#30]
**Feature Summary**

We need to make sure we're following best practices with our React code.

**Questions to Answer**

- How can we switch from using components to hooks?
- How can we improve on overall reusablility/reduce redundancy?
- What is the best way to organize the code for UI related to database tables vs UI used throughout (menus, headers, modals, etc.)?
- What is the best way to handle routing?
- What is the best way to pass down data (info from the database)/handlers?

**Comment by section14** [comment]
To update this task's progress: I'm currently compiling a list of recommendations for the React code. I'll have answers for these questions, along with suggestions that extend beyond them. Since this code base is new to me, I'm trying to be as deliberate and thorough as I can with my assessment. I expect to have a preliminary list ready for review early next week.

**Comment by rolltidehero** [comment]
Is this the most important part of the new 2.0 system?

**Comment by JediKev** [comment]
@rolltidehero 

Not necessarily. This is a whole codebase rewrite so everything is the most important part lol

But yes, React is what we are using for the front-end and provides massive improvements in UI/UX capabilities.

Cheers.

**Comment by aydreeihn** [comment]
Completed
