### ISSUE TITLE
Dynamic List CRUD

### ISSUE THREAD

**Issue by aydreeihn** [osTicket/roadmap#8]
We need to add functionality to pull DynamicLists and DynamicListItems from the database as well as general CRUD functionality.

Current Tables Used:
- [ ] List
- [ ] ListItems
- [ ] Save an entry for the list in the Form table
- [ ] Save list properties to Form Field

Do we need to have the properties?

**Comment by aydreeihn** [comment]
Note: We have a model for list items, but we will have to do some extra work to pull ticket statuses from the ticket_status table.

**Comment by cjohnsonuk** [comment]
Would this allow setting up of different status lists per queue?  
So tickets in the data processing (eg received, authorised, processing added, QC, completed etc) can have different statuses to those in the software development queue (R&D, in coding, security testing, User acceptance testing, ready for push to live, pushed to live etc)

One list of statuses 
Each status can be linked to one or many queues so that when reporting across department with different queues is easy to pull out all the "Closed" tickets without having to choose each queue's own version of closed.

**Comment by JediKev** [comment]
@cjohnsonuk 

No, this is just adding core DynamicList functionality. However this is something we can add to our feature request list for possible future development.

Cheers.
